{% set name = "bats-core" %}
{% set version = "1.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bats-core/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: aeff09fdc8b0c88b3087c99de00cf549356d7a2f6a69e3fcec5e0e861d2f9063

build:
  number: 0

test:
  commands:
    - bash -c 'bats --help'
    - bash -c 'test "$(bats --version)" = "Bats {{ version }}"'

about:
  home: http://github.com/bats-core/bats-core
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'BATS: Bash Automated Testing System'

  description: |
    Bats is a TAP-compliant testing framework for Bash. It provides a simple way to
    verify that the UNIX programs you write behave as expected.
  dev_url: https://github.com/bats-core/bats-core

extra:
  recipe-maintainers:
    - sodre
